// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXnzKucISArPuw5kElRDmvrsXG5WprOrc',
    appId: '1:354766803550:web:98c65fae615a02c861dacf',
    messagingSenderId: '354766803550',
    projectId: 'coffeeshopmanagement-6aa72',
    authDomain: 'coffeeshopmanagement-6aa72.firebaseapp.com',
    storageBucket: 'coffeeshopmanagement-6aa72.appspot.com',
    measurementId: 'G-WB02274GX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7bnfsIzK7aqnjsnGG63gK5twrI8PYU0',
    appId: '1:354766803550:android:054b115ed823033461dacf',
    messagingSenderId: '354766803550',
    projectId: 'coffeeshopmanagement-6aa72',
    storageBucket: 'coffeeshopmanagement-6aa72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEwQ-0DNrV0BM6RV8PD1FUy5EI7moF4eI',
    appId: '1:354766803550:ios:14fdabbd0486c8f161dacf',
    messagingSenderId: '354766803550',
    projectId: 'coffeeshopmanagement-6aa72',
    storageBucket: 'coffeeshopmanagement-6aa72.appspot.com',
    iosBundleId: 'com.example.coffeeShopManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEwQ-0DNrV0BM6RV8PD1FUy5EI7moF4eI',
    appId: '1:354766803550:ios:14fdabbd0486c8f161dacf',
    messagingSenderId: '354766803550',
    projectId: 'coffeeshopmanagement-6aa72',
    storageBucket: 'coffeeshopmanagement-6aa72.appspot.com',
    iosBundleId: 'com.example.coffeeShopManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXnzKucISArPuw5kElRDmvrsXG5WprOrc',
    appId: '1:354766803550:web:5ebeb2fd80264fcc61dacf',
    messagingSenderId: '354766803550',
    projectId: 'coffeeshopmanagement-6aa72',
    authDomain: 'coffeeshopmanagement-6aa72.firebaseapp.com',
    storageBucket: 'coffeeshopmanagement-6aa72.appspot.com',
    measurementId: 'G-TRP0HJT6V5',
  );
}
